# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-19 19:11
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Pet Care', 'Pet Care'), ('Electrical', 'Electrical'), ('Garden', 'Garden')], default='test', max_length=26),
            preserve_default=False,
        ),
    ]
